#!/bin/sh
# Script d'installation "GestionLEDs"

# Variables
PACKAGE="GestionLEDs"
INSTALL_DIR="/usr/local/${PACKAGE}"
TMP_DIR="${SYNOPKG_PKGDEST}/../../@tmp"
SSS="/var/packages/${PACKAGE}/scripts/start-stop-status"
PATH="${INSTALL_DIR}/bin:/usr/local/bin:/bin:/usr/bin:/usr/syno/bin"
SERVICETOOL="/usr/syno/bin/servicetool"

preinst(){
    exit 0
}

postinst(){
    # Création du dossier s'il n'existe pas
    if [ ! -e "/var/packages/GestionLEDs" ]; then
        mkdir -p /var/packages/GestionLEDs
    fi

    # Changement des droits sur le dossier
    chown -R root:root /var/packages/GestionLEDs
    chmod a+x /var/packages/GestionLEDs/scripts/*

    # Lien
    ln -s ${SYNOPKG_PKGDEST} ${INSTALL_DIR}

    # Ajout du script en crontab
    if [ -e "/etc/crontab" ]; then
        echo -ne "00\t22\t*\t*\t*\troot\t/var/packages/GestionLEDs/scripts/start-stop-status stop\n" >> /etc/crontab
        echo -ne "00\t07\t*\t*\t*\troot\t/var/packages/GestionLEDs/scripts/start-stop-status start\n" >> /etc/crontab
    fi
    
    # Rechargement du service crond
    kill -USR1 $(ps | egrep -i "[c]rond" | awk '{print $1}')
    exit 0
}

preuninst(){
    # Remise en fonction des LEDs
    echo 4 > /dev/ttyS1
    echo 8 > /dev/ttyS1

    # Suppression de la crontab
    mv /etc/crontab /etc/crontab_old
    cat /etc/crontab_old | egrep -iv "GestionLEDs" > /etc/crontab
    rm -f /etc/crontab_old

    # Rechargement du service crond
    kill -USR1 $(ps | egrep -i "[c]rond" | awk '{print $1}')
    exit 0
}

postuninst(){
    # Suppression du dossier
    rm -Rf ${INSTALL_DIR}
    exit 0
}

preupgrade(){
    exit 0
}

postupgrade(){
    exit 0
}
